//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarMap.Cll.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarMap.Cll.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andromedae.
        /// </summary>
        internal static string And_G {
            get {
                return ResourceManager.GetString("And_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antliae.
        /// </summary>
        internal static string Ant_G {
            get {
                return ResourceManager.GetString("Ant_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apodis.
        /// </summary>
        internal static string Aps_G {
            get {
                return ResourceManager.GetString("Aps_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquilae.
        /// </summary>
        internal static string Aql_G {
            get {
                return ResourceManager.GetString("Aql_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquarii.
        /// </summary>
        internal static string Aqr_G {
            get {
                return ResourceManager.GetString("Aqr_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arae.
        /// </summary>
        internal static string Ara_G {
            get {
                return ResourceManager.GetString("Ara_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arietis.
        /// </summary>
        internal static string Ari_G {
            get {
                return ResourceManager.GetString("Ari_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurigae.
        /// </summary>
        internal static string Aur_G {
            get {
                return ResourceManager.GetString("Aur_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boötis.
        /// </summary>
        internal static string Boo_G {
            get {
                return ResourceManager.GetString("Boo_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caeli.
        /// </summary>
        internal static string Cae_G {
            get {
                return ResourceManager.GetString("Cae_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camelopardalis.
        /// </summary>
        internal static string Cam_G {
            get {
                return ResourceManager.GetString("Cam_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capricorni.
        /// </summary>
        internal static string Cap_G {
            get {
                return ResourceManager.GetString("Cap_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carinae.
        /// </summary>
        internal static string Car_G {
            get {
                return ResourceManager.GetString("Car_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassiopeiae.
        /// </summary>
        internal static string Cas_G {
            get {
                return ResourceManager.GetString("Cas_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centauri.
        /// </summary>
        internal static string Cen_G {
            get {
                return ResourceManager.GetString("Cen_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cephei.
        /// </summary>
        internal static string Cep_G {
            get {
                return ResourceManager.GetString("Cep_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceti.
        /// </summary>
        internal static string Cet_G {
            get {
                return ResourceManager.GetString("Cet_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamaeleontis.
        /// </summary>
        internal static string Cha_G {
            get {
                return ResourceManager.GetString("Cha_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circini.
        /// </summary>
        internal static string Cir_G {
            get {
                return ResourceManager.GetString("Cir_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canis Majoris.
        /// </summary>
        internal static string CMa_G {
            get {
                return ResourceManager.GetString("CMa_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canis Minoris.
        /// </summary>
        internal static string CMi_G {
            get {
                return ResourceManager.GetString("CMi_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancri.
        /// </summary>
        internal static string Cnc_G {
            get {
                return ResourceManager.GetString("Cnc_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columbae.
        /// </summary>
        internal static string Col_G {
            get {
                return ResourceManager.GetString("Col_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comae Berenices.
        /// </summary>
        internal static string Com_G {
            get {
                return ResourceManager.GetString("Com_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coronae Australis.
        /// </summary>
        internal static string CrA_G {
            get {
                return ResourceManager.GetString("CrA_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coronae Borealis.
        /// </summary>
        internal static string CrB_G {
            get {
                return ResourceManager.GetString("CrB_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crateris.
        /// </summary>
        internal static string Crt_G {
            get {
                return ResourceManager.GetString("Crt_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crucis.
        /// </summary>
        internal static string Cru_G {
            get {
                return ResourceManager.GetString("Cru_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corvi.
        /// </summary>
        internal static string Crv_G {
            get {
                return ResourceManager.GetString("Crv_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canum Venaticorum.
        /// </summary>
        internal static string CVn_G {
            get {
                return ResourceManager.GetString("CVn_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cygni.
        /// </summary>
        internal static string Cyg_G {
            get {
                return ResourceManager.GetString("Cyg_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delphini.
        /// </summary>
        internal static string Del_G {
            get {
                return ResourceManager.GetString("Del_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doradus.
        /// </summary>
        internal static string Dor_G {
            get {
                return ResourceManager.GetString("Dor_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draconis.
        /// </summary>
        internal static string Dra_G {
            get {
                return ResourceManager.GetString("Dra_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equulei.
        /// </summary>
        internal static string Equ_G {
            get {
                return ResourceManager.GetString("Equ_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eridani.
        /// </summary>
        internal static string Eri_G {
            get {
                return ResourceManager.GetString("Eri_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornacis.
        /// </summary>
        internal static string For_G {
            get {
                return ResourceManager.GetString("For_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geminorum.
        /// </summary>
        internal static string Gem_G {
            get {
                return ResourceManager.GetString("Gem_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruis.
        /// </summary>
        internal static string Gru_G {
            get {
                return ResourceManager.GetString("Gru_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herculis.
        /// </summary>
        internal static string Her_G {
            get {
                return ResourceManager.GetString("Her_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horologii.
        /// </summary>
        internal static string Hor_G {
            get {
                return ResourceManager.GetString("Hor_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrae.
        /// </summary>
        internal static string Hya_G {
            get {
                return ResourceManager.GetString("Hya_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydri.
        /// </summary>
        internal static string Hyi_G {
            get {
                return ResourceManager.GetString("Hyi_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indi.
        /// </summary>
        internal static string Ind_G {
            get {
                return ResourceManager.GetString("Ind_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lacertae.
        /// </summary>
        internal static string Lac_G {
            get {
                return ResourceManager.GetString("Lac_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leonis.
        /// </summary>
        internal static string Leo_G {
            get {
                return ResourceManager.GetString("Leo_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leporis.
        /// </summary>
        internal static string Lep_G {
            get {
                return ResourceManager.GetString("Lep_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librae.
        /// </summary>
        internal static string Lib_G {
            get {
                return ResourceManager.GetString("Lib_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leonis Minoris.
        /// </summary>
        internal static string LMi_G {
            get {
                return ResourceManager.GetString("LMi_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lupi.
        /// </summary>
        internal static string Lup_G {
            get {
                return ResourceManager.GetString("Lup_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyncis.
        /// </summary>
        internal static string Lyn_G {
            get {
                return ResourceManager.GetString("Lyn_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrae.
        /// </summary>
        internal static string Lyr_G {
            get {
                return ResourceManager.GetString("Lyr_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensae.
        /// </summary>
        internal static string Men_G {
            get {
                return ResourceManager.GetString("Men_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microscopii.
        /// </summary>
        internal static string Mic_G {
            get {
                return ResourceManager.GetString("Mic_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monocerotis.
        /// </summary>
        internal static string Mon_G {
            get {
                return ResourceManager.GetString("Mon_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscae.
        /// </summary>
        internal static string Mus_G {
            get {
                return ResourceManager.GetString("Mus_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normae.
        /// </summary>
        internal static string Nor_G {
            get {
                return ResourceManager.GetString("Nor_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octantis.
        /// </summary>
        internal static string Oct_G {
            get {
                return ResourceManager.GetString("Oct_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ophiuchi.
        /// </summary>
        internal static string Oph_G {
            get {
                return ResourceManager.GetString("Oph_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orionis.
        /// </summary>
        internal static string Ori_G {
            get {
                return ResourceManager.GetString("Ori_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pavonis.
        /// </summary>
        internal static string Pav_G {
            get {
                return ResourceManager.GetString("Pav_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegasi.
        /// </summary>
        internal static string Peg_G {
            get {
                return ResourceManager.GetString("Peg_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persei.
        /// </summary>
        internal static string Per_G {
            get {
                return ResourceManager.GetString("Per_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phoenicis.
        /// </summary>
        internal static string Phe_G {
            get {
                return ResourceManager.GetString("Phe_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictoris.
        /// </summary>
        internal static string Pic_G {
            get {
                return ResourceManager.GetString("Pic_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piscis Austrini.
        /// </summary>
        internal static string PsA_G {
            get {
                return ResourceManager.GetString("PsA_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piscium.
        /// </summary>
        internal static string Psc_G {
            get {
                return ResourceManager.GetString("Psc_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puppis.
        /// </summary>
        internal static string Pup_G {
            get {
                return ResourceManager.GetString("Pup_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyxidis.
        /// </summary>
        internal static string Pyx_G {
            get {
                return ResourceManager.GetString("Pyx_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reticuli.
        /// </summary>
        internal static string Ret_G {
            get {
                return ResourceManager.GetString("Ret_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sculptoris.
        /// </summary>
        internal static string Scl_G {
            get {
                return ResourceManager.GetString("Scl_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorpii.
        /// </summary>
        internal static string Sco_G {
            get {
                return ResourceManager.GetString("Sco_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scuti.
        /// </summary>
        internal static string Sct_G {
            get {
                return ResourceManager.GetString("Sct_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serpentis.
        /// </summary>
        internal static string Ser_G {
            get {
                return ResourceManager.GetString("Ser_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sextantis.
        /// </summary>
        internal static string Sex_G {
            get {
                return ResourceManager.GetString("Sex_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagittae.
        /// </summary>
        internal static string Sge_G {
            get {
                return ResourceManager.GetString("Sge_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagittarii.
        /// </summary>
        internal static string Sgr_G {
            get {
                return ResourceManager.GetString("Sgr_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tauri.
        /// </summary>
        internal static string Tau_G {
            get {
                return ResourceManager.GetString("Tau_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telescopii.
        /// </summary>
        internal static string Tel_G {
            get {
                return ResourceManager.GetString("Tel_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trianguli Australis.
        /// </summary>
        internal static string TrA_G {
            get {
                return ResourceManager.GetString("TrA_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trianguli.
        /// </summary>
        internal static string Tri_G {
            get {
                return ResourceManager.GetString("Tri_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tucanae.
        /// </summary>
        internal static string Tuc_G {
            get {
                return ResourceManager.GetString("Tuc_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ursae Majoris.
        /// </summary>
        internal static string UMa_G {
            get {
                return ResourceManager.GetString("UMa_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ursae Minoris.
        /// </summary>
        internal static string UMi_G {
            get {
                return ResourceManager.GetString("UMi_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velorum.
        /// </summary>
        internal static string Vel_G {
            get {
                return ResourceManager.GetString("Vel_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virginis.
        /// </summary>
        internal static string Vir_G {
            get {
                return ResourceManager.GetString("Vir_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volantis.
        /// </summary>
        internal static string Vol_G {
            get {
                return ResourceManager.GetString("Vol_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulpeculae.
        /// </summary>
        internal static string Vul_G {
            get {
                return ResourceManager.GetString("Vul_G", resourceCulture);
            }
        }
    }
}
